'''
import os
import sys

# Add the parent directory (src) to the system path to allow importing from Items and Locations
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

try:
    from Items import item_name_to_id
    from Locations import location_name_to_id
except ImportError as e:
    print("Error: Could not import from Items.py or Locations.py.")
    print("Please ensure this script is run from the project's root directory, or that the 'src' directory is in your PYTHONPATH.")
    print(e)
    sys.exit(1)


def generate_lua_data_file():
    """
    Reads item and location data from the Python APWorld files and generates
    a Lua file containing ID-to-name mappings for use by the client.
    """
    # Define the output path for the Lua file, inside a new 'lua' directory
    output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'lua'))
    output_path = os.path.join(output_dir, 'client_data.lua')

    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Invert the dictionaries to create ID-to-name mappings, which are more useful for the client
    id_to_item_name = {v: k for k, v in item_name_to_id.items()}
    id_to_location_name = {v: k for k, v in location_name_to_id.items()}

    print(f"Generating Lua client data at: {output_path}")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("-- This file is automatically generated by utils/generate_client_data.py. DO NOT EDIT.

")

        # Write item data
        f.write("AP_M1_ID_to_Item_Name = {
")
        # Sort by ID for consistent output
        for item_id, item_name in sorted(id_to_item_name.items()):
            # Escape single quotes in names for Lua syntax
            escaped_name = item_name.replace("'", "\'")
            f.write(f"    [{item_id}] = '{escaped_name}',
")
        f.write("}

")

        # Write location data
        f.write("AP_M1_ID_to_Location_Name = {
")
        # Sort by ID for consistent output
        for loc_id, loc_name in sorted(id_to_location_name.items()):
            escaped_name = loc_name.replace("'", "\'")
            f.write(f"    [{loc_id}] = '{escaped_name}',
")
        f.write("}
")

    print("Successfully generated client data.")


if __name__ == "__main__":
    generate_lua_data_file()
''